name: installer_info
description: Returns information about the method used to install your app.
version: 0.5.0
homepage: https://github.com/caiopo/flutter-installer-info
repository: https://github.com/caiopo/flutter-installer-info

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caiopo.installer_info
        pluginClass: InstallerInfoPlugin
      ios:
        pluginClass: InstallerInfoPlugin
